# Generated by Django 4.1.5 on 2023-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('phono', models.CharField(max_length=250, verbose_name='Mobile Number')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('state', models.CharField(max_length=250, verbose_name='State')),
                ('course', models.CharField(max_length=250, verbose_name='Course')),
            ],
        ),
    ]
